version: "3.5"

services:
  postgres:
    container_name: onlineStore-MarcLopez-P4
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: marc
      POSTGRES_PASSWORD: Password1234
      POSTGRES_DB: ${POSTGRES_DB:-playground}
      PGDATA: /data/postgres
    volumes:
      - postgres_vol:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres_net

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: marc@lopez.com
      PGADMIN_DEFAULT_PASSWORD: Password1234
    volumes:
      - pgadmin_vol:/root/.pgadmin
    ports:
      - ${PGADMIN_PORT:-5050}:80
    networks:
      - postgres_net

networks:
  postgres_net:
    driver: bridge

volumes:
  postgres_vol:
  pgadmin_vol:
